In [ ]:
import numpy as np

In [ ]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [ ]:
y=np.array([[1],[0],[1]])
y

array([[1],
       [0],
       [1]])

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
def derivative_sigmoid(x):
  return x*(1-x)

In [ ]:
epoch=5000
lr=0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [ ]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wo=np.random.uniform(size=(hidden_neurons,output_neurons))
bo=np.random.uniform(size=(1,output_neurons))

In [ ]:
for i in range(epoch):
  #forward
  hidden_input=np.dot(x,wh)
  hidden_input=hidden_input+bh
  hidden_activation=sigmoid(hidden_input)
  output_layer=np.dot(hidden_activation,wo)
  output=sigmoid(output_layer)
  #backward
  E=y-output
  slope_output=derivative_sigmoid(output)
  slope_hidden=derivative_sigmoid(hidden_activation)
  d_output=E*slope_output
  error_hidden=d_output.dot(wo.T)
  d_hidden=error_hidden*slope_hidden
  wo+=hidden_activation.T.dot(d_output)*lr
  bo+=np.sum(d_output,axis=0,keepdims=True)*lr
  wh+=x.T.dot(d_hidden)*lr
  bh+=np.sum(d_hidden,axis=0,keepdims=True)*lr

In [ ]:
output

array([[0.95228127],
       [0.07240675],
       [0.95442057]])

In [ ]:
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Standardize features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# One-hot encode labels
y_one_hot = tf.keras.utils.to_categorical(y, num_classes=3)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_one_hot, test_size=0.2, random_state=42)

# Define the neural network architecture using Functional API
inputs = tf.keras.Input(shape=(4,))
hidden_layer = tf.keras.layers.Dense(16, activation='relu')(inputs)
hidden_layer = tf.keras.layers.Dropout(0.2)(hidden_layer)  # Adding Dropout for regularization
output_layer = tf.keras.layers.Dense(3, activation='softmax')(hidden_layer)

# Create the model
model = tf.keras.Model(inputs=inputs, outputs=output_layer)

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.1)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')


Epoch 1/100
4/4 [==============================] - 1s 83ms/step - loss: 1.0584 - accuracy: 0.3981 - val_loss: 1.0043 - val_accuracy: 0.4167
Epoch 2/100
4/4 [==============================] - 0s 23ms/step - loss: 1.0868 - accuracy: 0.3796 - val_loss: 0.9823 - val_accuracy: 0.5000
Epoch 3/100
4/4 [==============================] - 0s 22ms/step - loss: 1.0335 - accuracy: 0.4259 - val_loss: 0.9622 - val_accuracy: 0.5000
Epoch 4/100
4/4 [==============================] - 0s 22ms/step - loss: 0.9708 - accuracy: 0.5093 - val_loss: 0.9428 - val_accuracy: 0.5000
Epoch 5/100
4/4 [==============================] - 0s 19ms/step - loss: 0.9956 - accuracy: 0.5185 - val_loss: 0.9243 - val_accuracy: 0.5833
Epoch 6/100
4/4 [==============================] - 0s 22ms/step - loss: 0.9652 - accuracy: 0.4815 - val_loss: 0.9059 - val_accuracy: 0.5833
Epoch 7/100
4/4 [==============================] - 0s 22ms/step - loss: 0.9439 - accuracy: 0.5463 - val_loss: 0.8881 - val_accuracy: 0.5833
Epoch 8/100
4/4 [===

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions=model(x_train[:1]).numpy()
predictions

array([[0.51774454, 0.09231597, 0.45476723, 0.76539063, 0.5212706 ,
        0.32809237, 0.5137121 , 0.133837  , 0.09987022, 0.12963833]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.11470264, 0.07495698, 0.10770173, 0.14693482, 0.1151078 ,
        0.09488739, 0.11424104, 0.07813479, 0.07552537, 0.07780742]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.3550644

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2983 - accuracy: 0.9127
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1466 - accuracy: 0.9559
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1093 - accuracy: 0.9664
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0916 - accuracy: 0.9718
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0782 - accuracy: 0.9750


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])